version: "2"
checks:
  method-complexity:
    config:
      threshold: 8
plugins:
  sonar-python:
    enabled: true
    config:
      minimum_severity: minor
      tests_patterns:
        - tests/**
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
          mass_threshold: 128

exclude_patterns:
- "tests/"
- "**/__init__.py"
