exclude: 'docs|.git|.toml|examples'
fail_fast: true
default_language_version:
  python: python3.7

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      -   id: trailing-whitespace
      -   id: check-merge-conflict
      -   id: check-yaml
      -   id: detect-private-key
      -   id: end-of-file-fixer
  - repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports']
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        args: [--line-length, '120']
        language_version: python3.7
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
      - id: mypy
        exclude: ^tests/
        verbose: true
