[tool.poetry]
name = "gata"
version = "2.1.0"
description = "Gata is data validation and transformation library for python."
authors = [
    "Dawid Kraczkowski <dawid.kraczkowski@gmail.com>"
]
license = "MIT"
readme = "README.md"

homepage = "https://github.com/kodemore/gata"
repository = "https://github.com/kodemore/gata"
documentation = "https://github.com/kodemore/gata"

keywords = ["validation", "schema", "dataclass", "formatter"]

classifiers = [
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

# Requirements
[tool.poetry.dependencies]
python = "^3.7"
pytest-cov = "^2.8.1"
coverage = "^4.5.4"
pydantic = "^1.3"

[tool.poetry.dev-dependencies]
pytest = "^4.1.0"
pytest-cov = "^2.5"
pytest-mock = "^1.9"
mypy = "^0.730.0"
black = { version = "^19.3b0", python = "^3.6" }
