name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        id: tag
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Build release
        with:
          python-version: "3.8"
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          make build
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: gata-${{ steps.tag.outputs.tag }}.tar.gz
          path: dist/gata-${{ steps.tag.outputs.tag }}.tar.gz
      - name: Publish release
        with:
          python-version: "3.8"
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          source $HOME/.poetry/env
          python -m pip install --upgrade pip
          pip install poetry
          make publish

